SDOSAlamofire+JSON:API
SDOSLabs/SDOSAlamofire pull request #1
Opened 2019-09-26 12:45 UTC by JMVelazquezGlez

2019-09-26 12:49 UTC, Lukanor commented
Falta:
- Indentar correctamente
- Añadir como se instala

2019-09-27 05:35 UTC, JMVelazquezGlez commented
> Falta:
> 
> * Indentar correctamente
> * Añadir como se instala

Corregida la organización del README

2019-09-27 05:46 UTC, RafaelFernandezAlv requested changes
Change readme.md

2019-09-27 05:51 UTC, RafaelFernandezAlv approved these changes

2019-09-27 05:57 UTC, RafaelFernandezAlv approved these changes

2019-09-27 05:58 UTC, merged